FROM ubuntu:20.04
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y build-essential vim cmake git wget tmux zlib1g zlib1g-dev libbz2-dev libffi-dev libreadline-dev libsqlite3-dev lzma  liblzma-dev libbz2-dev sudo libssl-dev libglib2.0-0 libgl1

# RUN useradd -ms /bin/bash -g root -G sudo dev
# RUN echo "dev:dev"|chpasswd

RUN useradd -u 1001 -ms /bin/bash -g  root -G sudo mitsuzaw
RUN echo "mitsuzaw:dev"|chpasswd

RUN apt install -y software-properties-common
RUN apt install -y python3-dev libeigen3-dev libgtest-dev libosgearth-dev ffmpeg default-jdk cmake python g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev swig

ENV SUMO_HOME="/opt/sumo/sumo-1_14_0"

WORKDIR /opt/sumo/
RUN wget https://github.com/eclipse-sumo/sumo/archive/refs/tags/v1_14_0.tar.gz
RUN tar -xvf v1_14_0.tar.gz
RUN cd ${SUMO_HOME} && mkdir build/cmake-build && cd build/cmake-build && cmake ../.. && make -j$(nproc)


USER mitsuzaw
WORKDIR /home/mitsuzaw

# install pyenv
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
RUN echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc
# adding sumo
RUN echo -e 'export SUMO_HOME="/opt/sumo/sumo-1_14_0"'
RUN echo -e 'export PATH="${SUMO_HOME}/bin:${PATH}"' >> ~/.bashrc

# git clone Monaco Project
WORKDIR /home/mitsuzaw
RUN git clone https://github.com/lcodeca/MoSTScenario.git

