[Resoruce]
    [Resoruce.output]
        path_output_resource = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/heavy-blocking-scenario/simple-aggregation/0/'
        path_output_png = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/heavy-blocking-scenario/simple-png/0/'
        path_output_heatmap = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/heavy-blocking-scenario/heatmap-png/0/'

    [Resoruce.input_x]
        path_simulation_output = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/heavy-blocking-scenario/postprocess/0/x/edge_time_loss.npz'
        key_name_lane_or_edge_id_vector = 'edge_id'
    [Resoruce.input_y]
        path_simulation_output = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/heavy-blocking-scenario/postprocess/0/y/edge_time_loss.npz'
        key_name_lane_or_edge_id_vector = 'edge_id'

[Aggregation]
    n_time_bucket = 500
    threshold_aggregation_value = 1.0