path_sumo_sim_xml = '/home/mitsuzaw/codes/dev/sumo-sim-monaco/simulation_extractions/sumo_configs/base/until_afternoon/original_config/sumo_cfg.cfg'
path_sumo_net_xml = '/home/mitsuzaw/codes/dev/sumo-sim-monaco/simulation_extractions/sumo_configs/base/until_afternoon/original_config/in/most.net.xml'
path_weight_jsonl = '/media/DATA/mitsuzaw/project_papers/project_data_centric/sumo_monaco/0/edge_waiting_time/output_jsons/edge_waiting_time/wasserstein_independence-.jsonl'

# Output
path_output_geo_file = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/heavy-blocking-scenario/geo_files/wasserstein_independence/edge_waiting_time.csv'

# Configurations
export_geofile_format = 'kepler.gl-csv'
lane_or_egde = 'edge'
n_time_bucket = 500
observation_every_step_per = 10