[Resource]
    path_simulation_output = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/slow_speed_scenario_iter/postprocess/0/x/load_observation.npz'
    path_output_jsonl = '/home/kensuke_mit/sumo-sim-outputs/aggregation.jsonl'

[Aggregation]
    n_time_bucket = 600
    threshold_aggregation_value = 1.0