[Resource]
    path_simulation_output = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/standard-and-sardine/postprocess/0/y/edge_waiting_time.npz'
    path_output_jsonl = '/media/DATA/mitsuzaw/sumo-sim-monaco-scenario/until_afternoon/standard-and-sardine/simple-aggregation/0/y/edge_waiting_time.jsonl'

    key_name_lane_or_edge_id_vector = 'edge_id'


[Aggregation]
    n_time_bucket = 600
    threshold_aggregation_value = 1.0